# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md


# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/rTreutlein/IsoSyntax
    commit: ebf2739edfac4568943edad389760386fe6535b5
  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [list-tries-0.6.3]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.10.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: []
# extra-lib-dirs: []

resolver: lts-8.5

#resolver: lts-7.19
#compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
#compiler-check: match-exact

#setup-info:
#  ghcjs:
#    source:
#      ghcjs-0.2.1.9007019_ghc-8.0.1:
#           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
#           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
